In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn import metrics

In [2]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


In [3]:
data = np.array([
    [-1, -1],
    [-2, -1],
    [-1, -2],
    [0, 0],
    [2, 1],
    [2, 3]
])

In [4]:
from sklearn.cluster import AgglomerativeClustering
clustering = AgglomerativeClustering().fit(data)

In [6]:
clustering.labels_

array([0, 0, 0, 0, 1, 1])

In [36]:
from sklearn.cluster import KMeans
cluster_kmeans = KMeans(n_init=1, n_clusters=2).fit(data)

In [37]:
cluster_kmeans.labels_

array([1, 1, 1, 0, 0, 0], dtype=int32)

In [9]:
cluster_kmeans.cluster_centers_

array([[-1., -1.],
       [ 2.,  2.]])

In [29]:
from sklearn.cluster import DBSCAN
cluster_dbscan = DBSCAN(eps=2, min_samples=2).fit(data)

In [30]:
cluster_dbscan.labels_

array([0, 0, 0, 0, 1, 1])

In [38]:
from sklearn.metrics import silhouette_score

In [40]:
silhouette_score(data, cluster_kmeans.labels_)

0.45993283428643883

In [45]:
from sklearn.decomposition import PCA
pca = PCA()
pca.fit(data)

PCA()

In [47]:
print(pca.singular_values_)

[5.29513029 1.40056959]


In [48]:
pca.components_

array([[ 0.67944959,  0.73372219],
       [-0.73372219,  0.67944959]])

In [49]:
B = pca.transform(data)

In [51]:
print(B)

[[-1.41317178  0.05427259]
 [-2.09262138  0.78799478]
 [-2.14689397 -0.625177  ]
 [ 0.          0.        ]
 [ 2.09262138 -0.78799478]
 [ 3.56006575  0.57090441]]


In [62]:
for j in [list_1, list_2, list_3, list_4]:
    error = []
    for i in range(len(B)):
        error.append(abs(B[i][0] - j[i]))
    print(sum(error))
#for i in B:
#    print(i[0])

0.6214548112827021
0.7300000000000002
1.2436564359571705
1.1351112472398723


In [56]:
list_1 = [-1.34, -1.98, -2.46, 0.00, 2.09, 3.68]
list_2 = [-1.34, -2.46, -1.98, 0.00, 2.09, 3.68]
list_3 = [-1.67, -2.46, -1.65, 0.00, 2.09, 3.68]
list_4 = [-1.67, -1.65, -2.46, 0.00, 2.09, 3.68]